### ISSUE TITLE
转录视频时提示临时文件正在被另一个程序使用，进程无法访问

### ISSUE THREAD

**Issue by Noire-Black-Heart** [NINIYOYYO/NeMo-ASR-GUI#4]
使用的是方法2，一步一步把pytorch装到虚拟环境里，本机的cuda是128，装了128和121的pytorch，都是同样的问题。环境下 cuda is available 返回是true

警告：转录文件 123.mp4 未生成有效的时间戳。正在跳过此文件。

[NeMo I 2025-12-23 00:05:53 nemo_logging:393] PADDING: 0
[NeMo I 2025-12-23 00:05:56 nemo_logging:393] Using RNNT Loss : tdt
    Loss tdt_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0, 'durations': [0, 1, 2, 3, 4], 'sigma': 0.02, 'omega': 0.1}
[NeMo I 2025-12-23 00:05:56 nemo_logging:393] Using RNNT Loss : tdt
    Loss tdt_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0, 'durations': [0, 1, 2, 3, 4], 'sigma': 0.02, 'omega': 0.1}
[NeMo I 2025-12-23 00:05:56 nemo_logging:393] Using RNNT Loss : tdt
    Loss tdt_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0, 'durations': [0, 1, 2, 3, 4], 'sigma': 0.02, 'omega': 0.1}
[NeMo I 2025-12-23 00:05:57 nemo_logging:393] Model EncDecRNNTBPEModel was successfully restored from F:\Whispers模型\parakeet-tdt-0.6b-v3.nemo.
00:05:57 - config_manager.py :  77 -  INFO - 配置已保存到 F:\parakeet-tdt-0.6b-v2-SRT-GUI\config.json
00:06:04 - transcription_controller.py:  50 -  INFO - 开始处理视频/音频文件， 当前: 1/1, 文件名: 123.mp4
00:06:05 - audio_processor.py:  60 -  INFO - 音频提取成功到: C:\Users\zhang\AppData\Local\Temp\tmpkstn0m3r.wav
00:06:05 - asr_service.py    :  78 -  INFO - 正在加载音频文件 'C:\Users\zhang\AppData\Local\Temp\tmpkstn0m3r.wav' 进行分块处理...
00:06:05 - asr_service.py    :  87 -  INFO - 音频总时长: 979.75 秒
[NeMo I 2025-12-23 00:06:05 nemo_logging:393] Timestamps requested, setting decoding timestamps to True. Capture them in Hypothesis object,                         with output[0][idx].timestep['word'/'segment'/'char']
00:06:05 - asr_service.py    : 102 -  INFO - 处理音频块: 0.00s - 60.00s
[NeMo I 2025-12-23 00:06:05 nemo_logging:393] Using RNNT Loss : tdt
    Loss tdt_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0, 'durations': [0, 1, 2, 3, 4], 'sigma': 0.02, 'omega': 0.1}
[NeMo W 2025-12-23 00:06:05 nemo_logging:405] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2025-12-23 00:06:05 nemo_logging:405] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
00:06:05 - cutset.py         : 721 -  INFO - Initializing Lhotse CutSet from a single NeMo manifest
            (is_tarred=False): 'C:\Users\zhang\AppData\Local\Temp\tmpb4l1kpz8\manifest.json'
Transcribing: 0it [00:01, ?it/s]
00:06:06 - asr_service.py    : 139 -  INFO - 转录音频块 'C:\Users\zhang\AppData\Local\Temp\tmppo7rieha.wav' 时发生错误: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\zhang\\AppData\\Local\\Temp\\tmpb4l1kpz8\\manifest.json'
Traceback (most recent call last):
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\collections\asr\parts\mixins\transcription.py", line 370, in transcribe_generator
    processed_outputs = self._transcribe_output_processing(model_outputs, transcribe_cfg)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\collections\asr\models\rnnt_models.py", line 944, in _transcribe_output_processing
    hyp = self.decoding.rnnt_decoder_predictions_tensor(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\collections\asr\parts\submodules\rnnt_decoding.py", line 717, in rnnt_decoder_predictions_tensor
    hypotheses_list = self.decoding(
                      ^^^^^^^^^^^^^^
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\collections\asr\parts\submodules\rnnt_greedy_decoding.py", line 201, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\core\classes\common.py", line 1204, in wrapped_call
    outputs = wrapped(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\collections\asr\parts\submodules\rnnt_greedy_decoding.py", line 2887, in forward
    hypotheses = self._greedy_decode(
                 ^^^^^^^^^^^^^^^^^^^^
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\collections\asr\parts\submodules\rnnt_greedy_decoding.py", line 2927, in _greedy_decode_blank_as_pad_loop_labels
    batched_hyps, alignments, batched_state = self.decoding_computer(
                                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\collections\asr\parts\submodules\transducer_decoding\label_looping_base.py", line 217, in __call__
    return self.cuda_graphs_impl(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\collections\asr\parts\submodules\transducer_decoding\tdt_label_looping.py", line 765, in cuda_graphs_impl
    self._graph_reinitialize(encoder_output, encoder_output_length)
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\collections\asr\parts\submodules\transducer_decoding\tdt_label_looping.py", line 946, in _graph_reinitialize
    self._full_graph_compile()
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\collections\asr\parts\submodules\transducer_decoding\tdt_label_looping.py", line 1029, in _full_graph_compile
    capture_status, _, graph, _, _, _ = cu_call(
                                        ^^^^^^^^
  File "F:\parakeet-tdt-0.6b-v2-SRT-GUI\.venv\Lib\site-packages\nemo\core\utils\cuda_python_utils.py", line 101, in cu_call
    raise Exception(f"CUDA failure! {error}")
Exception: CUDA failure! 35

查了一下35是cuda和显卡不匹配？ 但我3060ti用nvidia-smi查看显示的cuda版本是1.28啊

**Comment by NINIYOYYO** [comment]
你可以试试重新clone这个项目后，创建个虚拟环境 进入然后pip install -r requirements.txt 使用CPU版本转录一下， 看是不是能正常使用。

**Comment by NINIYOYYO** [comment]
如果能正常使用，文件不锁了，但依然直接报 CUDA failure 35说明问题确实出在GPU上，并且你需要GPU来转录的话，可以试试 更新 NVIDIA 驱动到最新然后pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 （在虚拟环境下运行），在看看行不行？

**Comment by Noire-Black-Heart** [comment]
> 你可以试试重新clone这个项目后，创建个虚拟环境 进入然后pip install -r requirements.txt 使用CPU版本转录一下， 看是不是能正常使用。

CPU版本完全可以正常使用，我现在就是在用CPU。 也没有说报过cuda failure，直接就是cuda is not available了，不管怎么说用CPU也比隔壁faster whisper快N倍，好顶赞_(:з)∠)_

**Comment by surfincanoy** [comment]
> > 你可以试试重新clone这个项目后，创建个虚拟环境 进入然后pip install -r requirements.txt 使用CPU版本转录一下， 看是不是能正常使用。
> 
> CPU版本完全可以正常使用，我现在就是在用CPU。 也没有说报过cuda failure，直接就是cuda is not available了，不管怎么说用CPU也比隔壁faster whisper快N倍，好顶赞_(:з)∠)_

排查以下情况：
一、硬件不支持高版本的CUDA，比如我的笔记本1060显卡，最高支持到CUDA：12.6版本，即使安装高版本的也无济于事。
二、驱动问题，安装CUDA时，13.0版本前的安装程序是可以安装显卡驱动的，但这个驱动可能存在问题，建议N卡官网下载安装显卡驱动。
另外，显卡驱动可以安装最新版本的，因为显卡驱动是兼容旧版CUDA的。nvidia-smi显示的是显卡驱动支持的CUDA最高版本，不是硬件支持的最高版本，这个要注意。
